import fs from "node:fs";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

// HTTPS is required for iOS Safari to allow navigator.geolocation, even on a
// local LAN IP over what would otherwise be plain HTTP. The cert/key here are
// generated by mkcert (see scripts/generate-certs.sh and README.md) so the
// browser trusts them instead of showing a self-signed-cert warning.
// server.host exposes the dev server on the LAN so it's reachable from a phone.
const certPath = "certs/dev-cert.pem";
const keyPath = "certs/dev-key.pem";

if (!fs.existsSync(certPath) || !fs.existsSync(keyPath)) {
  throw new Error(
    `Missing ${certPath}/${keyPath}. Run ./scripts/generate-certs.sh first — see README.md.`
  );
}

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: "autoUpdate",
      manifest: {
        name: "Tree Identifier",
        short_name: "TreeID",
        start_url: ".",
        display: "standalone",
        background_color: "#ffffff",
        theme_color: "#2e7d32",
        icons: [],
      },
      workbox: {
        // model.onnx can be large; make sure it's precached for offline use
        // once inference has run at least once.
        globPatterns: ["**/*.{js,css,html,onnx}"],
      },
    }),
  ],
  server: {
    host: true,
    https: {
      cert: fs.readFileSync(certPath),
      key: fs.readFileSync(keyPath),
    },
  },
});
